"""
Pydantic schemas
"""
from .auth import (
    UserRegister,
    UserLogin,
    TokenRefresh,
    PasswordResetRequest,
    PasswordReset,
    PasswordChange,
    UserResponse,
    OrganizationResponse,
    TokenResponse,
    MessageResponse,
    ErrorResponse,
)

from .campaign import (
    CampaignStatusEnum,
    CampaignGoalEnum,
    ObjectiveTypeEnum,
    KPINameEnum,
    CampaignObjectiveCreate,
    CampaignObjectiveUpdate,
    CampaignObjectiveResponse,
    CampaignCreate,
    CampaignUpdate,
    CampaignResponse,
    CampaignListResponse,
    CampaignScheduleRequest,
    CampaignStatsResponse,
)

from .ai_generation import (
    AIJobStatus,
    AIJobType,
    ToneEnum,
    LengthEnum,
    PersonalizationLevel,
    AIGenerationOptions,
    AIGenerationRequest,
    AIRefinementRequest,
    SubjectLineVariantsRequest,
    EmailVariant,
    AIGenerationResponse,
    SubjectLineVariant,
    SubjectLineVariantsResponse,
    AIGenerationJobList,
)

__all__ = [
    # Auth
    "UserRegister",
    "UserLogin",
    "TokenRefresh",
    "PasswordResetRequest",
    "PasswordReset",
    "PasswordChange",
    "UserResponse",
    "OrganizationResponse",
    "TokenResponse",
    "MessageResponse",
    "ErrorResponse",
    # Campaign
    "CampaignStatusEnum",
    "CampaignGoalEnum",
    "ObjectiveTypeEnum",
    "KPINameEnum",
    "CampaignObjectiveCreate",
    "CampaignObjectiveUpdate",
    "CampaignObjectiveResponse",
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignResponse",
    "CampaignListResponse",
    "CampaignScheduleRequest",
    "CampaignStatsResponse",
    # AI Generation
    "AIJobStatus",
    "AIJobType",
    "ToneEnum",
    "LengthEnum",
    "PersonalizationLevel",
    "AIGenerationOptions",
    "AIGenerationRequest",
    "AIRefinementRequest",
    "SubjectLineVariantsRequest",
    "EmailVariant",
    "AIGenerationResponse",
    "SubjectLineVariant",
    "SubjectLineVariantsResponse",
    "AIGenerationJobList",
]