"""Initial schema

Revision ID: 95d0f8a235fe
Revises: 
Create Date: 2025-12-29 00:15:31.659356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95d0f8a235fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Organization name'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='Organization email domain'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='Industry vertical'),
    sa.Column('company_size', sa.String(length=50), nullable=True, comment='Company size category: startup, small, medium, enterprise'),
    sa.Column('website_url', sa.String(length=500), nullable=True, comment='Company website'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether organization is active'),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False, comment='Subscription tier: beta, starter, pro, enterprise'),
    sa.Column('ai_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI model preferences and settings'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('company_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Reference to organization'),
    sa.Column('brand_voice', sa.Text(), nullable=True, comment='Description of brand voice and tone'),
    sa.Column('value_propositions', sa.ARRAY(sa.Text()), nullable=True, comment='Key value propositions'),
    sa.Column('pain_points', sa.ARRAY(sa.Text()), nullable=True, comment='Customer pain points the company solves'),
    sa.Column('competitive_advantages', sa.ARRAY(sa.Text()), nullable=True, comment='Competitive advantages'),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Target audience details: personas, industries, company sizes'),
    sa.Column('product_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Products and services offered'),
    sa.Column('brand_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Brand guidelines including colors, fonts, writing style'),
    sa.Column('compliance_requirements', sa.ARRAY(sa.Text()), nullable=True, comment='Compliance requirements: GDPR, CAN-SPAM, industry-specific'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('contacts',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Reference to organization'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Contact email address'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='First name'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Last name'),
    sa.Column('company', sa.String(length=255), nullable=True, comment='Company name'),
    sa.Column('job_title', sa.String(length=255), nullable=True, comment='Job title'),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True, comment='Tags for segmentation'),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom fields for flexible data'),
    sa.Column('subscription_status', sa.String(length=50), nullable=False, comment='Subscription status'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether email is verified'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_contact_email')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_subscription_status'), 'contacts', ['subscription_status'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Reference to organization'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (login)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='User full name'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='User role: owner, admin, member, viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Last login timestamp'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='User preferences: UI settings, notifications, etc.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Reference to organization'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action performed: campaign_created, email_sent, etc.'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Entity type: campaign, template, contact'),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='ID of the entity affected'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Before/after snapshot of changes'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP address of request'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent string'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False, comment='When action was performed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_org', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Reference to organization'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the campaign'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Campaign name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Campaign description'),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'REVIEW', 'SCHEDULED', 'SENDING', 'SENT', 'PAUSED', 'ARCHIVED', name='campaignstatus', native_enum=False, length=50), nullable=False, comment='Campaign status'),
    sa.Column('primary_goal', sa.String(length=100), nullable=False, comment='Primary campaign goal'),
    sa.Column('target_audience_description', sa.Text(), nullable=True, comment='Description of target audience'),
    sa.Column('success_criteria', sa.Text(), nullable=True, comment='Success criteria for the campaign'),
    sa.Column('target_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Target metrics: open_rate, click_rate, conversion_rate'),
    sa.Column('estimated_recipients', sa.Integer(), nullable=True, comment='Estimated number of recipients'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='When campaign is scheduled to send'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='When campaign was actually sent'),
    sa.Column('ai_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI generation context and parameters'),
    sa.Column('generation_iterations', sa.Integer(), nullable=False, comment='Number of AI generation iterations'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_scheduled_at'), 'campaigns', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('contact_lists',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Reference to organization'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='List name'),
    sa.Column('description', sa.Text(), nullable=True, comment='List description'),
    sa.Column('total_contacts', sa.Integer(), nullable=False, comment='Total number of contacts in list'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the list'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_lists_organization_id'), 'contact_lists', ['organization_id'], unique=False)
    op.create_table('campaign_analytics',
    sa.Column('campaign_id', sa.UUID(), nullable=False, comment='Reference to campaign'),
    sa.Column('total_sent', sa.Integer(), nullable=False, comment='Total emails sent'),
    sa.Column('total_delivered', sa.Integer(), nullable=False, comment='Total emails delivered'),
    sa.Column('total_bounced', sa.Integer(), nullable=False, comment='Total bounced emails'),
    sa.Column('total_failed', sa.Integer(), nullable=False, comment='Total failed sends'),
    sa.Column('total_opens', sa.Integer(), nullable=False, comment='Total opens (including duplicates)'),
    sa.Column('unique_opens', sa.Integer(), nullable=False, comment='Unique opens'),
    sa.Column('total_clicks', sa.Integer(), nullable=False, comment='Total clicks (including duplicates)'),
    sa.Column('unique_clicks', sa.Integer(), nullable=False, comment='Unique clicks'),
    sa.Column('total_unsubscribes', sa.Integer(), nullable=False, comment='Total unsubscribes'),
    sa.Column('total_spam_reports', sa.Integer(), nullable=False, comment='Total spam complaints'),
    sa.Column('delivery_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Delivery rate percentage'),
    sa.Column('open_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Open rate percentage'),
    sa.Column('click_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Click rate percentage'),
    sa.Column('click_to_open_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Click-to-open rate percentage'),
    sa.Column('unsubscribe_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Unsubscribe rate percentage'),
    sa.Column('goal_achieved', sa.Boolean(), nullable=False, comment='Whether campaign goal was achieved'),
    sa.Column('goal_completion_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Goal completion percentage'),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True, comment='Last time analytics were calculated'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('campaign_objectives',
    sa.Column('campaign_id', sa.UUID(), nullable=False, comment='Reference to campaign'),
    sa.Column('objective_type', sa.String(length=100), nullable=False, comment='Type: primary, secondary'),
    sa.Column('description', sa.Text(), nullable=False, comment='Objective description'),
    sa.Column('kpi_name', sa.String(length=100), nullable=False, comment='KPI name: open_rate, click_rate, conversion, revenue'),
    sa.Column('target_value', sa.Float(), nullable=False, comment='Target value for the KPI'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority level (1 = highest)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_objectives_campaign_id'), 'campaign_objectives', ['campaign_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('campaign_id', sa.UUID(), nullable=False, comment='Reference to campaign'),
    sa.Column('contact_id', sa.UUID(), nullable=False, comment='Reference to contact'),
    sa.Column('send_status', sa.String(length=50), nullable=False, comment='Send status: pending, sent, failed, bounced'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='When email was sent'),
    sa.Column('opened', sa.Boolean(), nullable=False, comment='Whether email was opened'),
    sa.Column('open_count', sa.Integer(), nullable=False, comment='Number of times opened'),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True, comment='First open timestamp'),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True, comment='Last open timestamp'),
    sa.Column('clicked', sa.Boolean(), nullable=False, comment='Whether any link was clicked'),
    sa.Column('click_count', sa.Integer(), nullable=False, comment='Number of clicks'),
    sa.Column('first_clicked_at', sa.DateTime(timezone=True), nullable=True, comment='First click timestamp'),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True, comment='Last click timestamp'),
    sa.Column('unsubscribed', sa.Boolean(), nullable=False, comment='Whether recipient unsubscribed'),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True, comment='Unsubscribe timestamp'),
    sa.Column('personalized_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Personalized content for this recipient'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contact')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_clicked'), 'campaign_recipients', ['clicked'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_contact_id'), 'campaign_recipients', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_opened'), 'campaign_recipients', ['opened'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_send_status'), 'campaign_recipients', ['send_status'], unique=False)
    op.create_table('contact_list_members',
    sa.Column('contact_id', sa.UUID(), nullable=False, comment='Reference to contact'),
    sa.Column('list_id', sa.UUID(), nullable=False, comment='Reference to contact list'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default='now()', nullable=False, comment='When contact was added to list'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'list_id', name='uq_contact_list')
    )
    op.create_index(op.f('ix_contact_list_members_contact_id'), 'contact_list_members', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_list_members_list_id'), 'contact_list_members', ['list_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('campaign_id', sa.UUID(), nullable=False, comment='Reference to campaign'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for tracking iterations'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='Whether this is the current active version'),
    sa.Column('subject_line', sa.String(length=255), nullable=False, comment='Email subject line'),
    sa.Column('preview_text', sa.String(length=150), nullable=True, comment='Email preview text (preheader)'),
    sa.Column('from_name', sa.String(length=255), nullable=True, comment='Sender name'),
    sa.Column('from_email', sa.String(length=255), nullable=True, comment='Sender email address'),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True, comment='Reply-to email address'),
    sa.Column('html_content', sa.Text(), nullable=True, comment='HTML email content'),
    sa.Column('plain_text_content', sa.Text(), nullable=True, comment='Plain text email content'),
    sa.Column('generated_by', sa.String(length=50), nullable=False, comment='Content generation source: ai, human, hybrid'),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True, comment='AI model used for generation'),
    sa.Column('generation_prompt', sa.Text(), nullable=True, comment='Prompt used for AI generation'),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI generation metadata: temperature, tokens, confidence'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Template status'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='User who reviewed the template'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='When template was reviewed'),
    sa.Column('review_notes', sa.Text(), nullable=True, comment='Review notes and feedback'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the template'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_campaign_version')
    )
    op.create_index(op.f('ix_email_templates_campaign_id'), 'email_templates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_templates_is_current'), 'email_templates', ['is_current'], unique=False)
    op.create_index(op.f('ix_email_templates_status'), 'email_templates', ['status'], unique=False)
    op.create_table('ai_generation_jobs',
    sa.Column('campaign_id', sa.UUID(), nullable=False, comment='Reference to campaign'),
    sa.Column('template_id', sa.UUID(), nullable=True, comment='Reference to generated template (if completed)'),
    sa.Column('job_type', sa.String(length=50), nullable=False, comment='Type: initial_generation, revision, ab_variant, subject_line_test'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending, processing, completed, failed'),
    sa.Column('user_prompt', sa.Text(), nullable=True, comment="User's generation prompt"),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Generation context: company profile, campaign objectives'),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Generated content variants'),
    sa.Column('ai_model', sa.String(length=100), nullable=True, comment='AI model used'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score of generation'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When job started processing'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When job completed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if job failed'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Number of tokens used'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who initiated the job'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_jobs_campaign_id'), 'ai_generation_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_status'), 'ai_generation_jobs', ['status'], unique=False)
    op.create_table('email_events',
    sa.Column('campaign_recipient_id', sa.UUID(), nullable=False, comment='Reference to campaign recipient'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Event type: sent, delivered, opened, clicked, bounced, unsubscribed, complained'),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Event-specific data: link_url, bounce_type, user_agent, etc.'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default='now()', nullable=False, comment='When event occurred'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False, comment='When event was recorded'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.ForeignKeyConstraint(['campaign_recipient_id'], ['campaign_recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_events_occurred', 'email_events', ['occurred_at'], unique=False)
    op.create_index('idx_email_events_recipient', 'email_events', ['campaign_recipient_id'], unique=False)
    op.create_index('idx_email_events_type', 'email_events', ['event_type'], unique=False)
    op.create_table('email_revisions',
    sa.Column('template_id', sa.UUID(), nullable=False, comment='Reference to email template'),
    sa.Column('revision_type', sa.String(length=50), nullable=False, comment='Type: ai_regeneration, manual_edit, ab_variant'),
    sa.Column('previous_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of previous version'),
    sa.Column('changes_made', sa.Text(), nullable=True, comment='Description of changes made'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for revision'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the revision'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_revisions_template_id'), 'email_revisions', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_revisions_template_id'), table_name='email_revisions')
    op.drop_table('email_revisions')
    op.drop_index('idx_email_events_type', table_name='email_events')
    op.drop_index('idx_email_events_recipient', table_name='email_events')
    op.drop_index('idx_email_events_occurred', table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_ai_generation_jobs_status'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_campaign_id'), table_name='ai_generation_jobs')
    op.drop_table('ai_generation_jobs')
    op.drop_index(op.f('ix_email_templates_status'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_is_current'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_campaign_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_contact_list_members_list_id'), table_name='contact_list_members')
    op.drop_index(op.f('ix_contact_list_members_contact_id'), table_name='contact_list_members')
    op.drop_table('contact_list_members')
    op.drop_index(op.f('ix_campaign_recipients_send_status'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_opened'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_contact_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_clicked'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_campaign_objectives_campaign_id'), table_name='campaign_objectives')
    op.drop_table('campaign_objectives')
    op.drop_table('campaign_analytics')
    op.drop_index(op.f('ix_contact_lists_organization_id'), table_name='contact_lists')
    op.drop_table('contact_lists')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_scheduled_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_org', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contacts_subscription_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('company_profiles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
